
package clientews.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioMaquinaDosWS", targetNamespace = "http://beans/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioMaquinaDosWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "potencia", targetNamespace = "http://beans/", className = "clientews.servicio.Potencia")
    @ResponseWrapper(localName = "potenciaResponse", targetNamespace = "http://beans/", className = "clientews.servicio.PotenciaResponse")
    @Action(input = "http://beans/ServicioMaquinaDosWS/potenciaRequest", output = "http://beans/ServicioMaquinaDosWS/potenciaResponse")
    public int potencia(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "coseno", targetNamespace = "http://beans/", className = "clientews.servicio.Coseno")
    @ResponseWrapper(localName = "cosenoResponse", targetNamespace = "http://beans/", className = "clientews.servicio.CosenoResponse")
    @Action(input = "http://beans/ServicioMaquinaDosWS/cosenoRequest", output = "http://beans/ServicioMaquinaDosWS/cosenoResponse")
    public double coseno(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seno", targetNamespace = "http://beans/", className = "clientews.servicio.Seno")
    @ResponseWrapper(localName = "senoResponse", targetNamespace = "http://beans/", className = "clientews.servicio.SenoResponse")
    @Action(input = "http://beans/ServicioMaquinaDosWS/senoRequest", output = "http://beans/ServicioMaquinaDosWS/senoResponse")
    public double seno(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tangente", targetNamespace = "http://beans/", className = "clientews.servicio.Tangente")
    @ResponseWrapper(localName = "tangenteResponse", targetNamespace = "http://beans/", className = "clientews.servicio.TangenteResponse")
    @Action(input = "http://beans/ServicioMaquinaDosWS/tangenteRequest", output = "http://beans/ServicioMaquinaDosWS/tangenteResponse")
    public double tangente(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "raiz", targetNamespace = "http://beans/", className = "clientews.servicio.Raiz")
    @ResponseWrapper(localName = "raizResponse", targetNamespace = "http://beans/", className = "clientews.servicio.RaizResponse")
    @Action(input = "http://beans/ServicioMaquinaDosWS/raizRequest", output = "http://beans/ServicioMaquinaDosWS/raizResponse")
    public int raiz(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invertidas", targetNamespace = "http://beans/", className = "clientews.servicio.Invertidas")
    @ResponseWrapper(localName = "invertidasResponse", targetNamespace = "http://beans/", className = "clientews.servicio.InvertidasResponse")
    @Action(input = "http://beans/ServicioMaquinaDosWS/invertidasRequest", output = "http://beans/ServicioMaquinaDosWS/invertidasResponse")
    public int invertidas(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
