
package clientews.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioSumarWS", targetNamespace = "http://beans/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioSumarWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "porcentaje", targetNamespace = "http://beans/", className = "clientews.servicio.Porcentaje")
    @ResponseWrapper(localName = "porcentajeResponse", targetNamespace = "http://beans/", className = "clientews.servicio.PorcentajeResponse")
    @Action(input = "http://beans/ServicioSumarWS/porcentajeRequest", output = "http://beans/ServicioSumarWS/porcentajeResponse")
    public int porcentaje(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "promedio", targetNamespace = "http://beans/", className = "clientews.servicio.Promedio")
    @ResponseWrapper(localName = "promedioResponse", targetNamespace = "http://beans/", className = "clientews.servicio.PromedioResponse")
    @Action(input = "http://beans/ServicioSumarWS/promedioRequest", output = "http://beans/ServicioSumarWS/promedioResponse")
    public int promedio(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://beans/", className = "clientews.servicio.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://beans/", className = "clientews.servicio.SumarResponse")
    @Action(input = "http://beans/ServicioSumarWS/sumarRequest", output = "http://beans/ServicioSumarWS/sumarResponse")
    public int sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restar", targetNamespace = "http://beans/", className = "clientews.servicio.Restar")
    @ResponseWrapper(localName = "restarResponse", targetNamespace = "http://beans/", className = "clientews.servicio.RestarResponse")
    @Action(input = "http://beans/ServicioSumarWS/restarRequest", output = "http://beans/ServicioSumarWS/restarResponse")
    public int restar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicar", targetNamespace = "http://beans/", className = "clientews.servicio.Multiplicar")
    @ResponseWrapper(localName = "multiplicarResponse", targetNamespace = "http://beans/", className = "clientews.servicio.MultiplicarResponse")
    @Action(input = "http://beans/ServicioSumarWS/multiplicarRequest", output = "http://beans/ServicioSumarWS/multiplicarResponse")
    public int multiplicar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dividir", targetNamespace = "http://beans/", className = "clientews.servicio.Dividir")
    @ResponseWrapper(localName = "dividirResponse", targetNamespace = "http://beans/", className = "clientews.servicio.DividirResponse")
    @Action(input = "http://beans/ServicioSumarWS/dividirRequest", output = "http://beans/ServicioSumarWS/dividirResponse")
    public int dividir(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
